name: 'Sync'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'

    - name: Generate redirect
      id: page_url
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
        echo "url="${url/%?/} >> "$GITHUB_OUTPUT"

    - name: install builer
      run: go install github.com/concrnt/emojipack-builder@v0.0.3

    - name: build
      run: emojipack-builder
      env:
        BASE_URL: ${{ steps.page_url.outputs.url }}

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./

  # Deployment job
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4